### ISSUE TITLE
`AutomaticScan.svelte` omzetten in Atomic Design

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/future-ready-design#43]
> * zie https://github.com/SamaraFellaDina/future-ready-design/issues/46 door volledige uitleg

<img width="734" alt="image" src="https://github.com/user-attachments/assets/46b83778-cd74-4884-8ca3-4598cbc18466">

# omzetten naar _Atomic design_
Hoe ga ik dit component omzetten naar een atomic design

## Atoms
Wat zijn allemaal atoms?

<img width="869" alt="image" src="https://github.com/user-attachments/assets/916ed142-bd6b-45f1-9635-a81046314695">

Dit component bestaat eigenlijk uit 3 atomen:
* een `h2`
* een `p`
* en een `canvas` die een grafiek bevat

**Comment by SamaraFellaDina** [comment]
Nadat @J3SS3HVA mij wat advies gaf over mijn huidige schets, heb ik inderdaad gekozen om de `h2` en `p` los in het organismen te doen, aangezien dit statisch is. maar ik wil er nog wel in verdiepen

![Image](https://github.com/user-attachments/assets/345c6047-3199-4104-b5cb-4a5a9392a1bf)

**Comment by SamaraFellaDina** [comment]
# grafiek

<img width="494" alt="image" src="https://github.com/user-attachments/assets/e06b77a0-8062-483e-b7fa-39d6c0f07d22">

## Hoe zit de grafiek in elkaar?
door een breakdown te maken van de code, kom ik hier op uit:

* de `canvas` en de `figcaption` zijn allebei atoms
* de `figure is een molecule, omdat het samen een groep creëert.

**Comment by SamaraFellaDina** [comment]
De section van de grafiek ziet er nu zo uit:

```html
<section>
    <h2>{result.title}</h2>
    <p>{result.description}</p>
    <DonutChart {result}/>
</section>
```
Hierin zit dus nog een component waarin de grafiek word geïmporteerd

```html
<script>
  import { onMount } from "svelte";
  import Chart from "chart.js/auto";
  export let result = data.scans;

  let chart;
  let percentage = result.score;

  onMount(() => {
    let doughnutColor = percentage < 50 ? '#c30010' : percentage < 80 ? '#faa800' : '#228b22';
    let doughnutColorAlt = doughnutColor + "33";

    const data = {
      datasets: [
        {
          label: "Percentage",
          data: [percentage, 100 - percentage],
          backgroundColor: [doughnutColor, doughnutColorAlt],
          borderWidth: 0,
          cutout: "75%",
        },
      ],
    };

    const options = {
      plugins: {
        datalabels: {
          display: false,
        },
        tooltip: {
          enabled: false, // Enable tooltips
        },
      },
      responsive: false,
      maintainAspectRatio: true,
    };

    const ctx = document.getElementById("doughnut-chart").getContext("2d");
    chart = new Chart(ctx, {
      type: "doughnut",
      data: data,
      options: options,
    });
  });
</script>


<figure>
  <canvas id="doughnut-chart" height="150" width="150"></canvas>
  <figcaption>{percentage}%</figcaption>
</figure>

<style>
    canvas {
    max-width: 100%;
    height: auto;
  }

  figcaption {
    position: absolute;
    font-size: 2em;
    top: 52%;
    left: 50%; 
    transform: translate(-50%, -50%);
    font-weight: 700;
  }

  figure {
    position: relative;
    width: 100%;
    max-width: fit-content;
    height: min-content;
    align-self: center;
    
    @media screen and (max-width: 700px) {
      margin-top: 50px;
    }
  }

</style>
```

**Comment by SamaraFellaDina** [comment]
Voor nu ga ik even verder met #39 

* [ ] #39

**Comment by J3SS3HVA** [comment]
Netjes beschreven klopt het trouwens dat dat grote stuk code waarin de chart wort gemaakt een component file is met de naam DonutChart.svelte.

wat je hebt beschreven over wat een atoom is en wat een molecuul is heb je ook goed beschreven
