### ISSUE TITLE
ontwerpen van `scroll-driven-animation`

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/future-ready-design#69]
> * in #68 kan je zien wie welk concept heeft voor deze deeltaak

# Welke stappen horen bij deze opdracht?

## ontwerpen
1. Maak een tijdsinschatting en schiet issues in voor je taken (lees even verder)
2. [Doe vooronderzoek](https://github.com/SamaraFellaDina/future-ready-design/issues/69#issuecomment-2511553303) 
3. [Schets een wireflow ](https://github.com/SamaraFellaDina/future-ready-design/issues/69#issuecomment-2511697425)
4. [Maak een breakdown schets](https://github.com/SamaraFellaDina/future-ready-design/issues/69#issuecomment-2515481519)

## maken
> * deze stappen kan je vinden bij #80 
5. [Implementeer jouw concept in HTML/CSS/JS en Sveltekit.](https://github.com/SamaraFellaDina/future-ready-design/issues/80#issuecomment-2515511440) Beschrijf in de betreffende issue hoe je de belangrijkste dingen voor elkaar krijgt.
6. Test uitvoerig en beschrijf verschillen in performance in de betreffende issue.
7. Voer een pull-request uit waarin je de belangrijkste zaken uit bovenstaande issues opneemt. (nb. voer het PR nog niet door!)
8. Publiceer jouw project via Vercel of Netlify naast de bestaande site (je selecteert dan jouw aparte branch).
9. Laat je concept testen door de tribe bij een user-test tijdens de Design & Code review! Neem opmerkingen op in het pull-request. Voer opgedane inzichten door en voeg die als commits toe aan het pull-request.

# Welke concept heb ik?

<img width="624" alt="image" src="https://github.com/user-attachments/assets/6ce3d951-97b2-4f5f-8da9-cfe9dfa1ff17">

**Comment by SamaraFellaDina** [comment]
# Vooronderzoek

**Comment by SamaraFellaDina** [comment]
# Schets een wireflow
voor jouw concept, gebruik eventueel de morphologische kaart. Bedenk welke interacties, animaties en geluidsondersteuning je nodig hebt. Neem jouw schetsen op in de betreffende issue.

**Comment by SamaraFellaDina** [comment]
In commit https://github.com/SamaraFellaDina/future-ready-design/commit/26932dddc97c66c4a692989f571dc9371ada544b heb ik alvast een stijling klaargezet

![Image](https://github.com/user-attachments/assets/0db225bd-d903-4c6f-a6bc-f233d0a1c6d7)

**Comment by SamaraFellaDina** [comment]
# Maak een breakdownschets

waarin je onderzoekt hoe je jouw concept met HTML, CSS en Javascript kunt implementeren. Bespreek jouw schets met teamgenoten of docenten. Neem ook jouw breakdown schets op in de betreffende issue.

**Comment by zainablfz** [comment]
Je hebt goed vooronderzoek gedaan naar wat je prompt precies inhoudt en nagedacht wat hierbij past en geïmplementeerd in je pagina. Ook heb je uitgezocht wat voor scroll-animations er zijn en welke je zou kunnen gebruiken. Je eindresultaat ziet er goed uit en je animations zijn ook goed gelukt <3
