### ISSUE TITLE
Ontwerpen van een `view-transition`

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/future-ready-design#86]
> * In deeltaak SamaraFellaDina/future-ready-design#88 kan je zien wie welk concept maakt voor deze deeltaak

# Welke stappen horen bij deze opdracht? 
## Ontwerpen
1. Maak een tijdsinschatting en schiet issues in voor je taken (lees even verder)
2. [Doe vooronderzoek](https://github.com/SamaraFellaDina/lose-your-head-the-client-case/issues/145#issuecomment-2531115333)
3. [Schets een wireflow](https://github.com/SamaraFellaDina/lose-your-head-the-client-case/issues/145#issuecomment-2531139872)
4. [Maak een breakdownschets](https://github.com/SamaraFellaDina/lose-your-head-the-client-case/issues/145#issuecomment-2531356968)

## Maken
> * deze stappen kan je vinden bij #89 
5. Implementeer jouw concept in HTML/CSS/JS en Sveltekit. Beschrijf in de betreffende issue hoe je de belangrijkste dingen voor elkaar krijgt.
6. Test uitvoerig en beschrijf verschillen in performance in de betreffende issue.
7. Voer een pull-request uit waarin je de belangrijkste zaken uit bovenstaande issues opneemt. (nb. voer het PR nog niet door!)
8. Publiceer jouw project via Vercel of Netlify naast de bestaande site (je selecteert dan jouw aparte branch).
9. Laat je concept testen door de tribe bij een user-test tijdens de Design & Code review! Neem opmerkingen op in het pull-request. Voer opgedane inzichten door en voeg die als commits toe aan het pull-request.

# Welk concept heb ik? 

<img width="744" alt="Screenshot 2024-12-09 at 14 31 01" src="https://github.com/user-attachments/assets/e1f46c1b-1c2b-46fb-8e0e-5f33ee853108">

**Comment by SamaraFellaDina** [comment]
* in #87 , wou ik ook kijken hoe alles precies werkt

**Comment by zainablfz** [comment]
Je pagina is goed redesigned volgens de prompt en je view-transition is ook goed gelukt! Misschien zou het een leuke uitdaging zijn om iets te kunnen doen met het thema tijdens de view-transition?
